# Generated by Django 4.0 on 2022-02-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wulfi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
