# Generated by Django 4.0 on 2022-03-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wulfi', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(blank=True, to='wulfi.Tag'),
        ),
    ]
