# Generated by Django 4.0 on 2022-07-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wulfi', '0005_post_post_views_profile_profile_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
